version: 2
jobs:
  build:
    docker:
      - image: "fedora:latest"
    steps:
      - checkout
      - run:
          name: Installing Build Tool
          command: 'dnf install ninja-build gcc-c++ clang cmake -y'
      - run:
          name: Installing Linting Tool
          command: 'dnf install cppcheck python3 -y && pip3 install cpplint'
      - run:
          name: Install Library
          command: 'dnf install spdlog libasan libubsan gtest-devel gtest -y'
      - run:
          name: Build and Test
          command: chmod u+x build.sh && ./build.sh
          requires: 

#  workflows:
#    version: 2
#    one_and_two:
#      jobs:
#        - one
#        - two