version: 2
jobs:
  build:
    docker:
      - image: "fedora:latest"
    steps:
      - checkout
      - run:
          name: Installing dnf Tool
          command: 'dnf install spdlog libasan python3 ninja-build gcc cmake lib cppcheck gtest-devel gtest -y'
      - run:
          name: Installing cpplint Tool
          command: 'pip3 install cpplint'

#  workflows:
#    version: 2
#    one_and_two:
#      jobs:
#        - one
#        - two