version: 2
jobs:
  install_deps:
    docker:
      - image: "fedora:latest"
    steps:
      - checkout
      - run: 'dnf install ninja-build gcc-c++ clang cmake -y'
      - run: 'dnf install cppcheck python3 -y && pip3 install cpplint'
      - run: 'dnf install spdlog libasan libubsan gtest-devel gtest -y'
      - persist_to_workspace:
          root: hatter_workspace
          paths:
            - .

  cmake_build:
    docker:
      - image: "fedora:latest"
    steps:
      - checkout
      - attach_workspace:
          at: hatter_workspace
      - run: chmod u+x build.sh && ./build.sh

workflows:
  version: 2
  hatter_build:
    jobs:
      - install_deps
      - cmake_build:
          requires:
            - install_deps