version: 2
jobs:
  install_deps_and_build:
    docker:
      - image: "fedora:latest"
    steps:
      - checkout
      - run: dnf install ninja-build gcc-c++ clang cmake -y
      - run: dnf install cppcheck python3 -y && pip3 install cpplint
      - run: dnf install spdlog libasan libubsan gtest-devel gtest -y
      - run: chmod u+x build.sh && ./build.sh
      - persist_to_workspace:
          root: build
          paths:
            - .

  test:
    docker:
      - image: "fedora:latest"
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: chmod u+x test.sh && ./test.sh 

workflows:
  version: 2
  hatter_build:
    jobs:
      - install_deps_and_build
      - test:
          requires:
            - install_deps_and_build